version: '3.9'
services:
  httpflood:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - GO111MODULE=on
      - HTTPFLOOD_DB=/data/httpflood.sqlite
    volumes:
      - ./data:/data
