services:
  httpflood:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - GO111MODULE=on
      - HTTPFLOOD_DB=/data/httpflood.sqlite
      - HTTPFLOOD_ADMIN_USER=admin
      - HTTPFLOOD_ADMIN_PASS=Khang0834684568
    volumes:
      - ./data:/data
